### PR TITLE
mdx for osx

### PR DESCRIPTION
**Pull request by piyushrpt**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)

Attempt to build mdx for osx as well

### CODE REVIEW

**Comment by rtburns-jpl** [comment]
I think xorg-xproto is required to build mdx? `_X_DEPRECATED` should be defined in Xfuncproto.h

**Comment by piyushrpt** [comment]
I'm trying to track down where X11/Xlib.h etc are installed. They are already downloaded - just that scons doesnt find it. It can find all the motif libraries. Just the couple of motif header files are missing - probably in a different location

**Comment by piyushrpt** [comment]
The header Xfuncproto.h from conda looks significantly different and lacks a whole bunch of macros that are available in the macports version. Need to understand this better.

**Comment by piyushrpt** [comment]
Thanks for tracking this down. That seems like a ugly hack on the tk-feedstock

**Pull request merged**
